version: '3.4'

x-nodejs: &nodejs
  build:
    context: .
    dockerfile: ./Dockerfile
    args:
      NODE_VERSION_MAJOR: 12
  image: booking-dev:0.2.0
  tmpfs:
    - /tmp
  stdin_open: true
  tty: true

services:
  backend:
    <<: *nodejs
    command: yarn start
    volumes:
      - .:/app:cached
    environment:
      MONGODB_URL: mongodb://mongodb
    ports:
      - '8000:8000'
      - '9229:9229'
    depends_on:
      - mongodb

  frontend:
    <<: *nodejs
    command: yarn start
    volumes:
      - ./frontend:/app:cached
    ports:
      - '3000:3000'

  mongodb:
    image: mongo:4
    ports:
      - 27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
