version: '3.4'

x-nodejs: &nodejs
  build:
    context: .
    dockerfile: ./docker/Dockerfile
  image: booking-dev:0.1.0
  tmpfs:
    - /tmp
  stdin_open: true
  tty: true

services:
  backend:
    <<: *nodejs
    command: yarn start
    volumes:
      - .:/app:cached
      - backend-node_modules:/app/node_modules
    environment:
      MONGODB_URL: mongodb://mongodb
    ports:
      - '8000:8000'
    depends_on:
      - mongodb

  frontend:
    <<: *nodejs
    command: yarn start
    volumes:
      - ./frontend:/app:cached
      - frontend-node_modules:/app/node_modules
    ports:
      - '3000:3000'

  mongodb:
    image: mongo:4
    ports:
      - 27017
    volumes:
      - mongo-data:/data/db

volumes:
  backend-node_modules:
  frontend-node_modules:
  mongo-data:
